spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mycdb?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: myc
    password: myc1998
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
criterion:
  email: '^([a-z0-9A-Z]+[-|\.]?)+[a-z0-9A-Z]@([a-z0-9A-Z]+(-[a-z0-9A-Z]+)?\.)+[a-zA-Z]{2,}$'
  phone: '[1][358]\d{9}'
star:
  success:
    number: 1
    char: success
  fail:
    number: -1
    char: fail
  username: username
  password: password
  email: email
  phone: phone
  id: id
  time:
    number: 0
    char: time
  map:
    code: code
    data: data
    key: key
    type: type
  msg:
    send: send
    msg: msg
    time:
      old: 0
      new: 1
    type: type
    set: set
#配置日志
logging:
  level:
    #不同目录下的日志可配置不同级别
    org.springfromework.web: INFO
    org.hibernate: ERROR
    com.example.demo.dao: trace
  #采用相对路径方式将日志文件输出到【log/springboot.log】
  file:
    name: log/springboot.log

# 打印sql.log
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 9527
  servlet:
    context-path: /demo



